# Week 11: AI Recommendation Engine

Build logic for Buy/Sell/Hold decisions: Combine predicted return 

Design decision rules: Example: Buy if pred_return > 2%

First version of AI investor bot working.

Outputs recommendation with justification.


# Week 12: Final Report, UI & Presentation
Tasks:
Create final project report (PDF or notebook):


Methodology, analysis, ML models, sentiment impact


Prepare slides for final presentation.


Finalize Streamlit/Gradio app (optional).


Record demo (optional) and publish repo.


Milestones:
Complete GitHub repo with code + documentation.


Report, presentation, and optional web app submitted.

In [1]:
# 1) Task 1  — Build 'pred_combined' (pred_* avg → y_pred → lagged log return)
# 2) Task 2  — Apply decision rules (BUY if pred > +2%, SELL if pred < -2%, else HOLD)
# 3) Milestone 1 — First working AI investor bot (end-to-end)
# 4) Milestone 2 — Outputs recommendation with justification (saved snapshot)

# Outputs:
# - week11/task1_combined_pred_latest.csv
# - week11/task2_recommendations.csv / .md
# - week11/ai_bot_m1_recommendations.csv / .md
# - week11/milestone2_recommendations.csv / .md

import numpy as np
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown

REPORT_DIR = Path("week10")
OUT_DIR    = Path("week11")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# thresholds (log-return units; 0.002 ≈ +0.2%)
POS_THRESHOLD = 0.002
NEG_THRESHOLD = -0.002
ALLOW_SHORT   = False  # long-only; SELL => avoid/close long (no short)


def load_eval():
    """Load evaluation table (Parquet with CSV fallback), ensure Date dtype, sort."""
    pq, csv = REPORT_DIR / "eval_table.parquet", REPORT_DIR / "eval_table.csv"
    if pq.exists():
        try:
            df = pd.read_parquet(pq).copy()
        except Exception:
            if csv.exists():
                df = pd.read_csv(csv, parse_dates=["Date"]).copy()
            else:
                raise
    elif csv.exists():
        df = pd.read_csv(csv, parse_dates=["Date"]).copy()
    else:
        raise FileNotFoundError("Neither eval_table.parquet nor eval_table.csv found in week10/")
    if not pd.api.types.is_datetime64_any_dtype(df["Date"]):
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    return df.sort_values(["Ticker","Date"]).reset_index(drop=True)

def compute_pred_combined(df: pd.DataFrame) -> pd.Series:
    """
    Priority:
      1) mean of pred_* columns (excluding y_pred) if any
      2) else y_pred if present
      3) else naive = yesterday's log return from Close
    """
    pred_cols = [c for c in df.columns
                 if c.lower().startswith("pred_") and c != "y_pred"
                 and pd.api.types.is_numeric_dtype(df[c])]
    if pred_cols:
        return df[pred_cols].mean(axis=1)
    if "y_pred" in df.columns and pd.api.types.is_numeric_dtype(df["y_pred"]):
        return df["y_pred"]
    if "Close" in df.columns:
        logret = np.log(df["Close"] / df["Close"].shift(1))
        return logret.shift(1)
    raise ValueError("No prediction columns found and 'Close' missing; cannot build pred_combined.")

def decide_action(pred: float, pos_thr: float, neg_thr: float, allow_short: bool):
    """
    Stateless decision: returns (action, justification).
    action ∈ {"BUY","SELL","HOLD"}; with shorting OFF, SELL means avoid/close long.
    """
    if pred > pos_thr:
        return (
            "BUY",
            f"Predicted next-day log return {pred:.2%} > {pos_thr:.2%} threshold."
        )
    if pred < neg_thr:
        if allow_short:
            return (
                "SELL",
                f"Predicted next-day log return {pred:.2%} < {neg_thr:.2%}; open short."
            )
        else:
            return (
                "SELL",
                f"Predicted next-day log return {pred:.2%} < {neg_thr:.2%}; avoid/close long (no short)."
            )
    return (
        "HOLD",
        f"Predicted return within dead-zone [{neg_thr:.2%}, {pos_thr:.2%}]."
    )

# =============================================================================
# Combine predicted return
# =============================================================================
eval_df = load_eval()
eval_df["pred_combined"] = compute_pred_combined(eval_df)

task1_latest = (
    eval_df.groupby("Ticker", as_index=False)
           .tail(1)[["Ticker","Date","pred_combined"]]
           .sort_values("Ticker")
           .reset_index(drop=True)
)

display(Markdown("## Task 1 — Latest combined predicted next-day log return"))
display(task1_latest)

task1_csv = OUT_DIR / "task1_combined_pred_latest.csv"
task1_latest.to_csv(task1_csv, index=False)
print("Saved:", task1_csv)

# =============================================================================
# Design decision rules (±2% example)
# =============================================================================
task2_rows = []
for _, r in task1_latest.iterrows():
    pred = float(r["pred_combined"])
    action, reason = decide_action(pred, POS_THRESHOLD, NEG_THRESHOLD, ALLOW_SHORT)
    task2_rows.append({
        "Ticker": r["Ticker"],
        "Date":   pd.to_datetime(r["Date"]).date(),
        "pred_combined": pred,
        "Decision": action,
        "Justification": reason
    })
task2_recs = pd.DataFrame(task2_rows).sort_values("Ticker")

display(Markdown(f"## Task 2 — Recommendations (long-only)  \n"
                 f"Rule: BUY if pred > +{POS_THRESHOLD:.0%}, SELL if pred < {NEG_THRESHOLD:.0%}, else HOLD."))
display(task2_recs)

task2_csv = OUT_DIR / "task2_recommendations.csv"
task2_md  = OUT_DIR / "task2_recommendations.md"
task2_recs.to_csv(task2_csv, index=False)
md_lines = [
    "# Task 2 — Recommendations (long-only)\n\n",
    f"Rule: **BUY** if pred_combined > +{POS_THRESHOLD:.0%}, **SELL** if pred_combined < {NEG_THRESHOLD:.0%}, else **HOLD**.\n\n",
    "| Ticker | Date | pred_combined | Decision | Justification |\n",
    "|---|---|---:|---|---|\n",
]
for _, rr in task2_recs.iterrows():
    md_lines.append(f"| {rr.Ticker} | {rr.Date} | {rr.pred_combined:.5f} | {rr.Decision} | {rr.Justification} |\n")
task2_md.write_text("".join(md_lines), encoding="utf-8")
print("Saved:", task2_csv, "and", task2_md)

# =============================================================================
# First working AI investor bot (end-to-end)
# =============================================================================
m1_rows = []
for _, r in task1_latest.iterrows():
    pred = float(r["pred_combined"])
    action, reason = decide_action(pred, POS_THRESHOLD, NEG_THRESHOLD, ALLOW_SHORT)
    m1_rows.append({
        "Ticker": r["Ticker"],
        "Date":   pd.to_datetime(r["Date"]).date(),
        "pred_combined": pred,
        "Decision": action,
        "Justification": reason
    })
m1_recs = pd.DataFrame(m1_rows).sort_values("Ticker")

display(Markdown("## Milestone 1 — AI Investor Bot (2% / -2% rule, long-only)"))
display(m1_recs)

m1_csv = OUT_DIR / "ai_bot_m1_recommendations.csv"
m1_md  = OUT_DIR / "ai_bot_m1_recommendations.md"
m1_recs.to_csv(m1_csv, index=False)

md = [
    "# Milestone 1 — AI Investor Bot (2% / -2% rule, long-only)\n\n",
    f"Rule: **BUY** if pred_combined > +{POS_THRESHOLD:.0%}, **SELL** if pred_combined < {NEG_THRESHOLD:.0%}, else **HOLD**.\n\n",
    "| Ticker | Date | pred_combined | Decision | Justification |\n",
    "|---|---|---:|---|---|\n",
]
for _, rr in m1_recs.iterrows():
    md.append(f"| {rr.Ticker} | {rr.Date} | {rr.pred_combined:.5f} | {rr.Decision} | {rr.Justification} |\n")
Path(m1_md).write_text("".join(md), encoding="utf-8")
print("Saved:", m1_csv, "and", m1_md)

# =============================================================================
# Outputs recommendation with justification
# =============================================================================
m2_recs = m1_recs.copy()

display(Markdown("## Milestone 2 — Recommendations with justification (±2% rule)"))
display(m2_recs)

m2_csv = OUT_DIR / "milestone2_recommendations.csv"
m2_md  = OUT_DIR / "milestone2_recommendations.md"
m2_recs.to_csv(m2_csv, index=False)

md2 = [
    "# Milestone 2 — Recommendations with justification (±2% rule)\n\n",
    f"Rule: **BUY** if pred_combined > +{POS_THRESHOLD:.0%}, **SELL** if pred_combined < {NEG_THRESHOLD:.0%}, else **HOLD**.\n\n",
    "| Ticker | Date | pred_combined | Decision | Justification |\n",
    "|---|---|---:|---|---|\n",
]
for _, rr in m2_recs.iterrows():
    md2.append(f"| {rr.Ticker} | {rr.Date} | {rr.pred_combined:.5f} | {rr.Decision} | {rr.Justification} |\n")
Path(m2_md).write_text("".join(md2), encoding="utf-8")
print("Saved:", m2_csv, "and", m2_md)

## Task 1 — Latest combined predicted next-day log return

  Ticker       Date  pred_combined
0   AAPL 2025-07-09       0.000286
1   AMZN 2025-07-09      -0.018563
2    CRM 2025-07-09       0.014169
3  GOOGL 2025-07-09      -0.013840
4    IBM 2025-07-09      -0.007034
5   META 2025-07-09       0.003224
6   MSFT 2025-07-09      -0.002213
7   NVDA 2025-07-08      -0.006927
8   ORCL 2025-07-08      -0.021552
9   TSLA 2025-07-09       0.013080

Saved: week11/task1_combined_pred_latest.csv

## Task 2 — Recommendations (long-only)
Rule: BUY if pred > +0%, SELL if pred < -0%, else HOLD.

,Ticker,Date,pred_combined,Decision,Justification
0,AAPL,2025-07-09,0.000286,HOLD,"Predicted return within dead-zone [-0.20%, 0.2..."
1,AMZN,2025-07-09,-0.018563,SELL,Predicted next-day log return -1.86% < -0.20%;...
2,CRM,2025-07-09,0.014169,BUY,Predicted next-day log return 1.42% > 0.20% th...
3,GOOGL,2025-07-09,-0.013840,SELL,Predicted next-day log return -1.38% < -0.20%;...
4,IBM,2025-07-09,-0.007034,SELL,Predicted next-day log return -0.70% < -0.20%;...
5,META,2025-07-09,0.003224,BUY,Predicted next-day log return 0.32% > 0.20% th...
6,MSFT,2025-07-09,-0.002213,SELL,Predicted next-day log return -0.22% < -0.20%;...
7,NVDA,2025-07-08,-0.006927,SELL,Predicted next-day log return -0.69% < -0.20%;...
8,ORCL,2025-07-08,-0.021552,SELL,Predicted next-day log return -2.16% < -0.20%;...
9,TSLA,2025-07-09,0.013080,BUY,Predicted next-day log return 1.31% > 0.20% th...

Saved: week11/task2_recommendations.csv and week11/task2_recommendations.md

## Milestone 1 — AI Investor Bot (2% / -2% rule, long-only)

,Ticker,Date,pred_combined,Decision,Justification
0,AAPL,2025-07-09,0.000286,HOLD,"Predicted return within dead-zone [-0.20%, 0.2..."
1,AMZN,2025-07-09,-0.018563,SELL,Predicted next-day log return -1.86% < -0.20%;...
2,CRM,2025-07-09,0.014169,BUY,Predicted next-day log return 1.42% > 0.20% th...
3,GOOGL,2025-07-09,-0.013840,SELL,Predicted next-day log return -1.38% < -0.20%;...
4,IBM,2025-07-09,-0.007034,SELL,Predicted next-day log return -0.70% < -0.20%;...
5,META,2025-07-09,0.003224,BUY,Predicted next-day log return 0.32% > 0.20% th...
6,MSFT,2025-07-09,-0.002213,SELL,Predicted next-day log return -0.22% < -0.20%;...
7,NVDA,2025-07-08,-0.006927,SELL,Predicted next-day log return -0.69% < -0.20%;...
8,ORCL,2025-07-08,-0.021552,SELL,Predicted next-day log return -2.16% < -0.20%;...
9,TSLA,2025-07-09,0.013080,BUY,Predicted next-day log return 1.31% > 0.20% th...

Saved: week11/ai_bot_m1_recommendations.csv and week11/ai_bot_m1_recommendations.md

## Milestone 2 — Recommendations with justification (±2% rule)

,Ticker,Date,pred_combined,Decision,Justification
0,AAPL,2025-07-09,0.000286,HOLD,"Predicted return within dead-zone [-0.20%, 0.2..."
1,AMZN,2025-07-09,-0.018563,SELL,Predicted next-day log return -1.86% < -0.20%;...
2,CRM,2025-07-09,0.014169,BUY,Predicted next-day log return 1.42% > 0.20% th...
3,GOOGL,2025-07-09,-0.013840,SELL,Predicted next-day log return -1.38% < -0.20%;...
4,IBM,2025-07-09,-0.007034,SELL,Predicted next-day log return -0.70% < -0.20%;...
5,META,2025-07-09,0.003224,BUY,Predicted next-day log return 0.32% > 0.20% th...
6,MSFT,2025-07-09,-0.002213,SELL,Predicted next-day log return -0.22% < -0.20%;...
7,NVDA,2025-07-08,-0.006927,SELL,Predicted next-day log return -0.69% < -0.20%;...
8,ORCL,2025-07-08,-0.021552,SELL,Predicted next-day log return -2.16% < -0.20%;...
9,TSLA,2025-07-09,0.013080,BUY,Predicted next-day log return 1.31% > 0.20% th...

Saved: week11/milestone2_recommendations.csv and week11/milestone2_recommendations.md

In [2]:
pip install gradio pandas numpy

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting gradio
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/93/32/2b35e003c795770445c20b05ea3023c4932032d65a7e55193bdd084df083/gradio-5.43.1-py3-none-any.whl (59.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 MB 10.6 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)
Collecting aiofiles<25.0,>=22.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/a5/45/30bb92d442636f570cb5651bc661f52b610e2eec3f891a5dc3a4c3667db0/aiofiles-24.1.0-py3-none-any.whl (15 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (4.7.0)
Collecting audioop-lts<1.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/1b/83/ea581e364ce7b0d41456fb79d6ee0ad482beda61faf0cab20cbd4c63a541/audioop_lts-0.2.2-cp313-abi3-macosx_11_0_arm64.whl (26 kB)
Collecting brotli>=1.1.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/0a/9f/fb37bb8ffc52a8da37b1c03c459a8cd55df7a57bdccd8831d500e994a0ca/Brotli-1.1.0-cp313-cp313-macosx_10_13_universal2.whl (815 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 815.7/815.7 kB 19.2 MB/s eta 0:00:00
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/e5/47/d63c60f59a59467fda0f93f46335c9d18526d7071f025cb5b89d5353ea42/fastapi-0.116.1-py3-none-any.whl (95 kB)
Collecting ffmpy (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/74/d4/1806897b31c480efc4e97c22506ac46c716084f573aef780bb7fb7a16e8a/ffmpy-0.6.1-py3-none-any.whl (5.5 kB)
Collecting gradio-client==1.12.1 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/77/95/e248cabea8c5b1eaa69c0e4742e4d4cbb3708272670917daf8eef2f78aa1/gradio_client-1.12.1-py3-none-any.whl (324 kB)
Collecting groovy~=0.1 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/28/27/3d6dcadc8a3214d8522c1e7f6a19554e33659be44546d44a2f7572ac7d2a/groovy-0.1.2-py3-none-any.whl (14 kB)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (0.28.1)
Collecting huggingface-hub<1.0,>=0.33.5 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/39/7b/bb06b061991107cd8783f300adff3e7b7f284e330fd82f507f2a1417b11d/huggingface_hub-0.34.4-py3-none-any.whl (561 kB)
Requirement already satisfied: jinja2<4.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (3.0.2)
Collecting orjson~=3.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/c2/f3/0dd6b4750eb556ae4e2c6a9cb3e219ec642e9c6d95f8ebe5dc9020c67204/orjson-3.11.2-cp313-cp313-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (226 kB)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (24.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<2.12,>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (2.11.7)
Collecting pydub (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/a6/53/d78dc063216e62fc55f6b2eebb447f6a4b0a59f55c8406376f76bf959b08/pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/45/58/38b5afbc1a800eeea951b9285d3912613f2603bdf897a4ab0f4bd7f405fc/python_multipart-0.0.20-py3-none-any.whl (24 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (6.0.2)
Collecting ruff>=0.9.3 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/d7/f1/97f509b4108d7bae16c48389f54f005b62ce86712120fd8b2d8e88a7cb49/ruff-0.12.10-py3-none-macosx_11_0_arm64.whl (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 10.1 MB/s eta 0:00:00a 0:00:01
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/4d/c0/1108ad9f01567f66b3154063605b350b69c3c9366732e09e45f9fd0d1deb/safehttpx-0.1.6-py3-none-any.whl (8.7 kB)
Collecting semantic-version~=2.0 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/6a/23/8146aad7d88f4fcb3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/f7/1f/b876b1f83aef204198a42dc101613fefccb32258e5428b5f9259677864b4/starlette-0.47.2-py3-none-any.whl (72 kB)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (0.13.2)
Collecting typer<1.0,>=0.12 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/2d/76/06dbe78f39b2203d2a47d5facc5df5102d0561e2807396471b5f7c5a30a1/typer-0.16.1-py3-none-any.whl (46 kB)
Requirement already satisfied: typing-extensions~=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/d2/e2/dc81b1bd1dcfe91735810265e9d26bc8ec5da45b4c0f6237e286819194c3/uvicorn-0.35.0-py3-none-any.whl (66 kB)
Requirement already satisfied: fsspec in /opt/anaconda3/lib/python3.13/site-packages (from gradio-client==1.12.1->gradio) (2025.3.2)
Collecting websockets<16.0,>=10.0 (from gradio-client==1.12.1->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/ff/0b/33cef55ff24f2d92924923c99926dcce78e7bd922d649467f0eda8368923/websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.13/site-packages (from anyio<5.0,>=3.0->gradio) (3.7)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (3.17.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (4.67.1)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.33.5->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/70/72/ce898516e97341a7a9d450609e130e108643389110261eaee6deb1ba8545/hf_xet-1.1.8-cp37-abi3-macosx_11_0_arm64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 52.4 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<2.12,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<2.12,>=2.0->gradio) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<2.12,>=2.0->gradio) (0.4.0)
Requirement already satisfied: click>=8.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer<1.0,>=0.12->gradio) (1.5.0)
Requirement already satisfied: rich>=10.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->huggingface-hub<1.0,>=0.33.5->gradio) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->huggingface-hub<1.0,>=0.33.5->gradio) (2.3.0)
Installing collected packages: pydub, brotli, websockets, uvicorn, semantic-version, ruff, python-multipart, orjson, hf-xet, groovy, ffmpy, audioop-lts, aiofiles, starlette, huggingface-hub, typer, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: brotli
    Found existing installation: Brotli 1.0.9
    Uninstalling Brotli-1.0.9:
      Successfully uninstalled Brotli-1.0.9━━━━━━━━━━━━━━━━━━━━━━━  1/20 [brotli]
  Attempting uninstall: typer━━━━━━━╺━━━━━━━━━━━ 14/20 [huggingface-hub]
    Found existing installation: typer 0.9.00m━━━━━━━━━━━ 14/20 [huggingface-hub]
    Uninstalling typer-0.9.0:━━━╺━━━━━━━━━━━ 14/20 [huggingface-hub]
      Successfully uninstalled typer-0.9.0━━━━━━━━━━━ 14/20 [huggingface-hub]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20 [gradio]19/20 [gradio]-hub]
Successfully installed aiofiles-24.1.0 audioop-lts-0.2.2 brotli-1.1.0 fastapi-0.116.1 ffmpy-0.6.1 gradio-5.43.1 gradio-client-1.12.1 groovy-0.1.2 hf-xet-1.1.8 huggingface-hub-0.34.4 orjson-3.11.2 pydub-0.25.1 python-multipart-0.0.20 ruff-0.12.10 safehttpx-0.1.6 semantic-version-2.10.0 starlette-0.47.2 typer-0.16.1 uvicorn-0.35.0 websockets-15.0.1
Note: you may need to restart the kernel to use updated packages.

Collecting typing-extensions~=4.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/b5/00/d631e67a838026495268c2f6884f3711a15a9a2a96cd244fdaea53b823fb/typing_extensions-4.14.1-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: certifi in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from httpx<1.0,>=0.24.1->gradio) (2023.7.22)
Collecting httpcore==1.* (from httpx<1.0,>=0.24.1->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/7e/f5/f66802a942d491edb555dd61e3a9961140fd64c90bce1eafd741609d334d/httpcore-1.0.9-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 3.2 MB/s eta 0:00:00
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl (37 kB)
Requirement already satisfied: filelock in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (3.9.0)
Collecting fsspec (from gradio-client==1.12.1->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/2f/e0/014d5d9d7a4564cf1c40b5039bc882db69fd881111e03ab3657ac0b218e2/fsspec-2025.7.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.6/199.6 kB 18.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.33.5->gradio) (4.65.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.33.5->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/70/72/ce898516e97341a7a9d450609e130e108643389110261eaee6deb1ba8545/hf_xet-1.1.8-cp37-abi3-macosx_11_0_arm64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 31.5 MB/s eta 0:00:0000:0100:01
Collecting annotated-types>=0.6.0 (from pydantic<2.12,>=2.0->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.33.2 (from pydantic<2.12,>=2.0->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/24/2f/3cfa7244ae292dd850989f328722d2aef313f74ffc471184dc509e1e4e5a/pydantic_core-2.33.2-cp311-cp311-macosx_11_0_arm64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 36.5 MB/s eta 0:00:0000:01
Collecting typing-inspection>=0.4.0 (from pydantic<2.12,>=2.0->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/17/69/cd203477f944c353c31bade965f880aa1061fd6bf05ded0726ca845b6ff7/typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting anyio<5.0,>=3.0 (from gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/6f/12/e5e0282d673bb9746bacfb6e2dba8719989d3660cdb2ea79aee9a9651afb/anyio-4.10.0-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.2/107.2 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: click>=8.0.0 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from typer<1.0,>=0.12->gradio) (8.0.4)
Collecting shellingham>=1.3.0 (from typer<1.0,>=0.12->gradio)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/e0/f9/0595336914c5619e5f28a1fb793285925a8cd4b432c9da0a987836c7f822/shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich>=10.11.0 (from typer<1.0,>=0.12->gradio)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/e3/30/3c4d035596d3cf444529e0b2953ad0466f6049528a879d27534700580395/rich-14.1.0-py3-none-any.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.4/243.4 kB 8.7 MB/s eta 0:00:00
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.33.5->gradio) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.33.5->gradio) (1.26.16)
Requirement already satisfied: mdurl~=0.1 in /Users/liwenchen/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.0)
Installing collected packages: pydub, brotli, websockets, typing-extensions, tomlkit, shellingham, semantic-version, ruff, python-multipart, orjson, hf-xet, h11, groovy, fsspec, ffmpy, annotated-types, uvicorn, typing-inspection, rich, pydantic-core, huggingface-hub, httpcore, anyio, typer, starlette, pydantic, httpx, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: tomlkit
    Found existing installation: tomlkit 0.11.1
    Uninstalling tomlkit-0.11.1:
      Successfully uninstalled tomlkit-0.11.1
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.15.1
    Uninstalling huggingface-hub-0.15.1:
      Successfully uninstalled huggingface-hub-0.15.1
  Attempting uninstall: anyio
    Found existing installation: anyio 3.5.0
    Uninstalling anyio-3.5.0:
      Successfully uninstalled anyio-3.5.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.8
    Uninstalling pydantic-1.10.8:
      Successfully uninstalled pydantic-1.10.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.4.3 requires pyqt5<5.16, which is not installed.
spyder 5.4.3 requires pyqtwebengine<5.16, which is not installed.
jupyter-server 1.23.4 requires anyio<4,>=3.1.0, but you have anyio 4.10.0 which is incompatible.
anaconda-cloud-auth 0.1.3 requires pydantic<2.0, but you have pydantic 2.11.7 which is incompatible.
s3fs 2023.4.0 requires fsspec==2023.4.0, but you have fsspec 2025.7.0 which is incompatible.
Successfully installed annotated-types-0.7.0 anyio-4.10.0 brotli-1.1.0 fastapi-0.116.1 ffmpy-0.6.1 fsspec-2025.7.0 gradio-5.43.1 gradio-client-1.12.1 groovy-0.1.2 h11-0.16.0 hf-xet-1.1.8 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-0.34.4 orjson-3.11.2 pydantic-2.11.7 pydantic-core-2.33.2 pydub-0.25.1 python-multipart-0.0.20 rich-14.1.0 ruff-0.12.10 safehttpx-0.1.6 semantic-version-2.10.0 shellingham-1.5.4 starlette-0.47.2 tomlkit-0.13.3 typer-0.16.1 typing-extensions-4.14.1 typing-inspection-0.4.1 uvicorn-0.35.0 websockets-15.0.1
WARNING: There was an error checking the latest version of pip.
Note: you may need to restart the kernel to use updated packages.

In [3]:
# gradio
import io
import gradio as gr

REPORT_DIR = Path("week10")

def load_eval():
    pq, csv = REPORT_DIR / "eval_table.parquet", REPORT_DIR / "eval_table.csv"
    if pq.exists():
        try:
            df = pd.read_parquet(pq).copy()
        except Exception:
            if csv.exists():
                df = pd.read_csv(csv, parse_dates=["Date"]).copy()
            else:
                raise
    elif csv.exists():
        df = pd.read_csv(csv, parse_dates=["Date"]).copy()
    else:
        raise FileNotFoundError("Neither eval_table.parquet nor eval_table.csv found in week10/")
    if not pd.api.types.is_datetime64_any_dtype(df["Date"]):
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    return df.sort_values(["Ticker","Date"]).reset_index(drop=True)

def ensure_truth(df):
    if "target_next_log_return" in df.columns and pd.api.types.is_numeric_dtype(df["target_next_log_return"]):
        return df["target_next_log_return"]
    if "Close" in df.columns:
        logret = np.log(df["Close"] / df["Close"].shift(1))
        return logret.shift(-1)
    raise ValueError("Need target_next_log_return or Close for y_true")

def compute_pred_combined(df):
    pred_cols = [c for c in df.columns if c.lower().startswith("pred_") and c != "y_pred"
                 and pd.api.types.is_numeric_dtype(df[c])]
    if pred_cols: return df[pred_cols].mean(axis=1)
    if "y_pred" in df.columns and pd.api.types.is_numeric_dtype(df["y_pred"]): return df["y_pred"]
    if "Close" in df.columns:
        logret = np.log(df["Close"] / df["Close"].shift(1))
        return logret.shift(1)
    raise ValueError("No prediction columns and no Close; cannot build pred_combined.")

def decide_action(pred, pos_thr, neg_thr, allow_short):
    if pred > pos_thr:
        return ("BUY",  f"Pred {pred:.2%} > +{pos_thr:.2%}.")
    if pred < neg_thr:
        if allow_short: return ("SELL", f"Pred {pred:.2%} < {neg_thr:.2%}; open short.")
        return ("SELL", f"Pred {pred:.2%} < {neg_thr:.0%}; avoid/close long (no short).")
    return ("HOLD", f"Pred within dead-zone [{neg_thr:.0%}, +{pos_thr:.2%}].")

def run_bot(pos_thr_pct, neg_thr_pct, allow_short):
    pos_thr = pos_thr_pct / 100.0
    neg_thr = neg_thr_pct / 100.0

    df = load_eval()
    if "pred_combined" not in df.columns:
        df["pred_combined"] = compute_pred_combined(df)

    latest = df.groupby("Ticker", as_index=False).tail(1).reset_index(drop=True)

    rows = []
    for _, r in latest.iterrows():
        pred = float(r["pred_combined"])
        action, reason = decide_action(pred, pos_thr, neg_thr, allow_short)
        rows.append({
            "Ticker": r["Ticker"],
            "Date":   pd.to_datetime(r["Date"]).date(),
            "pred_combined": pred,
            "Decision": action,
            "Justification": reason
        })
    recs = pd.DataFrame(rows).sort_values("Ticker")

    csv_buf = io.StringIO()
    recs.to_csv(csv_buf, index=False)
    return recs, csv_buf.getvalue()

with gr.Blocks(title="AI Investor Bot") as demo:
    gr.Markdown("# AI Investor Bot — Quick Recommendations")
    with gr.Row():
        pos_thr = gr.Slider(0.0, 3.0, value=0.2, step=0.05, label="BUY threshold (+%)")
        neg_thr = gr.Slider(-3.0, 0.0, value=-0.2, step=0.05, label="SELL threshold (−%)")
        allow_s = gr.Checkbox(label="Allow shorting", value=False)
    run_btn = gr.Button("Run")
    out_tbl = gr.Dataframe(headers=["Ticker","Date","pred_combined","Decision","Justification"], wrap=True)
    out_csv = gr.File(label="Download CSV", visible=False)

    def _on_run(p, n, s):
        df, csv_text = run_bot(p, n, s)
        tmp = Path("latest_orders.csv")
        df.to_csv(tmp, index=False)
        return df, str(tmp)

    run_btn.click(_on_run, inputs=[pos_thr, neg_thr, allow_s], outputs=[out_tbl, out_csv])

if __name__ == "__main__":
    demo.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

# Update

In [11]:
# AI Investor Bot — Time-travel Portfolio (quality gate + risk-aware sizing)

from __future__ import annotations

import io
from pathlib import Path
import numpy as np
import pandas as pd
import gradio as gr

REPORT_DIR = Path("week10")
OUT_DIR    = Path("week11")
OUT_DIR.mkdir(parents=True, exist_ok=True)

def load_eval() -> pd.DataFrame:
    """Load eval table (Parquet with CSV fallback), ensure Date dtype, sort."""
    pq, csv = REPORT_DIR / "eval_table.parquet", REPORT_DIR / "eval_table.csv"
    if pq.exists():
        try:
            df = pd.read_parquet(pq).copy()
        except Exception:
            if csv.exists():
                df = pd.read_csv(csv, parse_dates=["Date"]).copy()
            else:
                raise
    elif csv.exists():
        df = pd.read_csv(csv, parse_dates=["Date"]).copy()
    else:
        raise FileNotFoundError("Neither eval_table.parquet nor eval_table.csv found in week10/")

    if not pd.api.types.is_datetime64_any_dtype(df["Date"]):
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

    return df.sort_values(["Ticker", "Date"]).reset_index(drop=True)

def ensure_truth(df: pd.DataFrame) -> pd.Series:
    """Return y_true = next-day log return (no leakage)."""
    if "target_next_log_return" in df.columns and pd.api.types.is_numeric_dtype(df["target_next_log_return"]):
        return df["target_next_log_return"]
    if "Close" in df.columns:
        logret = np.log(df["Close"] / df["Close"].shift(1))
        return logret.shift(-1)
    raise ValueError("Need target_next_log_return or Close for y_true.")

def compute_pred_combined(df: pd.DataFrame) -> pd.Series:
    """
    Priority:
      1) mean of pred_* columns (excluding y_pred) if any
      2) else y_pred if present
      3) else naive = yesterday's log return from Close
    """
    pred_cols = [
        c for c in df.columns
        if c.lower().startswith("pred_")
        and c != "y_pred"
        and pd.api.types.is_numeric_dtype(df[c])
    ]
    if pred_cols:
        return df[pred_cols].mean(axis=1)

    if "y_pred" in df.columns and pd.api.types.is_numeric_dtype(df["y_pred"]):
        return df["y_pred"]

    if "Close" in df.columns:
        logret = np.log(df["Close"] / df["Close"].shift(1))
        return logret.shift(1)

    raise ValueError("No prediction columns and no Close; cannot build pred_combined.")

def add_rolling_corr(df: pd.DataFrame, win: int, minp: int) -> pd.DataFrame:
    """Rolling corr(pred_combined, y_true) per ticker (no deprecated groupby.apply)."""
    df = df.copy()
    df["RollCorr"] = np.nan
    for _, idx in df.groupby("Ticker").groups.items():
        g = df.loc[idx].sort_values("Date")
        rc = g["pred_combined"].rolling(win, min_periods=minp).corr(g["y_true"])
        df.loc[g.index, "RollCorr"] = rc.values
    return df

# -----------------------------
# risk utilities
# -----------------------------
def daily_to_annual_vol(sig_daily: float) -> float:
    return float(sig_daily) * np.sqrt(252.0)

def annual_to_daily_vol(sig_annual: float) -> float:
    return float(sig_annual) / np.sqrt(252.0)

def cap_and_renorm(weights, cap=0.25, max_iter=20, tol=1e-12):
    """Cap weights at 'cap' and renormalize the rest (long-only)."""
    w = np.array(weights, dtype=float)
    if w.sum() <= 0:
        return np.zeros_like(w)
    w = w / w.sum()
    for _ in range(max_iter):
        over = w > cap
        if not np.any(over):
            break
        excess = w[over] - cap
        w[over] = cap
        remain = ~over
        rem_sum = w[remain].sum()
        if rem_sum < tol:
            break
        w[remain] = w[remain] + (w[remain] / rem_sum) * excess.sum()
    w = np.clip(w, 0.0, 1.0)
    s = w.sum()
    return w / s if s > tol else w

def build_base_weights(method, tickers, vol_series, preds=None, buy_thr=0.0):
    """
    method ∈ {"equal", "inverse_vol", "signal_vol"}
    - inverse_vol: weight ∝ 1/σ
    - signal_vol : weight ∝ max(pred - thr, 0) / σ
    """
    n = len(tickers)
    if n == 0:
        return np.array([])

    if method == "equal":
        return np.ones(n) / n

    if method in ("inverse_vol", "signal_vol"):
        v = np.array([max(vol_series.get(t, np.nan), np.nan) for t in tickers], dtype=float)
        if np.isnan(v).any() or (v <= 0).any():
            safe = np.where((v > 0) & np.isfinite(v), v, np.nan)
            fallback = np.nanmedian(safe) if np.isfinite(np.nanmedian(safe)) else 0.02
            v = np.where((v > 0) & np.isfinite(v), v, fallback)

        if method == "inverse_vol":
            inv = 1.0 / v
            return inv / inv.sum()

        # signal_vol
        s = np.array([max(float(preds[t]) - buy_thr, 0.0) for t in tickers], dtype=float)
        raw = s / v
        if raw.sum() <= 0:
            return np.ones(n) / n
        return raw / raw.sum()

    raise ValueError("Unknown method: use 'equal', 'inverse_vol', or 'signal_vol'.")

def portfolio_as_of(as_of_date: pd.Timestamp,
                    capital_usd: float,
                    buy_thr_pct: float,
                    corr_min: float,
                    method: str,
                    max_single_w_pct: float,
                    target_ann_vol_pct: float,
                    roll_corr_win: int,
                    roll_cov_win: int,
                    min_periods: int):
    """
    Returns: candidates_df, alloc_df, summary_df
    """
    pos_thr = buy_thr_pct / 100.0
    target_ann_vol = target_ann_vol_pct / 100.0
    max_single_w = max_single_w_pct / 100.0

    # Load & prep
    df = load_eval()
    if "pred_combined" not in df.columns:
        df["pred_combined"] = compute_pred_combined(df)
    if "y_true" not in df.columns:
        df["y_true"] = ensure_truth(df)

    df = df[df["Date"] <= pd.to_datetime(as_of_date)].copy()
    if df.empty:
        raise ValueError("No data up to the selected as-of date. Pick a later date.")
    df = add_rolling_corr(df, win=roll_corr_win, minp=min_periods)

    latest = (
        df.sort_values("Date")
          .groupby("Ticker", as_index=False)
          .tail(1)[["Ticker", "Date", "Close", "pred_combined", "RollCorr"]]
          .sort_values("Ticker")
          .reset_index(drop=True)
    )

    latest["Signal"] = (latest["pred_combined"] > pos_thr).astype(int)
    candidates = latest[(latest["Signal"] == 1) & (latest["RollCorr"] >= corr_min)].copy()
    pivot = df.pivot_table(index="Date", columns="Ticker", values="y_true", aggfunc="first").sort_index()
    win = pivot.tail(roll_cov_win)
    cov_all = win.cov(min_periods=min_periods)
    vol_all = win.std(axis=0)

    if candidates.empty:
        empty_alloc = pd.DataFrame(columns=["Ticker","Close","pred","actual_w","dollars","shares"])
        summary = pd.DataFrame([{
            "Capital ($)": round(capital_usd, 2),
            "Invested ($)": 0.0,
            "Cash ($)": round(capital_usd, 2),
            "Cash weight": 1.0,
            "Exp μ (daily, %)": 0.0,
            "Exp μ (annual, %)": 0.0,
            "Vol (daily, %)": 0.0,
            "Vol (annual, %)": 0.0,
            "Exp Sharpe": np.nan,
            "1-day 95% VaR ($)": 0.0,
            "Method": method,
            "Target Ann Vol": target_ann_vol,
            "Max Single W": max_single_w,
            "BUY thr": pos_thr,
            "Corr gate": corr_min,
        }])
        return (
            candidates[["Ticker","Date","Close","pred_combined","RollCorr"]],
            empty_alloc, summary
        )

    tickers = candidates["Ticker"].tolist()
    cov = cov_all.reindex(index=tickers, columns=tickers).copy()
    vol = vol_all.reindex(index=tickers)

    for t in tickers:
        if not np.isfinite(cov.loc[t, t]):
            var = float(vol.loc[t]**2) if np.isfinite(vol.loc[t]) else 0.0001
            cov.loc[t, t] = var
    cov = cov.fillna(0.0)

    closes = candidates.set_index("Ticker")["Close"].to_dict()
    preds  = candidates.set_index("Ticker")["pred_combined"].to_dict()

    base_w = build_base_weights(method, tickers, vol, preds=preds, buy_thr=pos_thr)
    base_w = cap_and_renorm(base_w, cap=max_single_w)

    # Vol targeting scale
    W = np.array(base_w, dtype=float)
    Sigma = cov.values
    port_vol_daily = float(np.sqrt(max(W @ Sigma @ W, 0.0)))
    target_daily = annual_to_daily_vol(target_ann_vol)
    scale = min(1.0, (target_daily / port_vol_daily)) if port_vol_daily > 0 else 0.0
    final_w = W * scale
    dollars = {t: float(final_w[i] * capital_usd) for i, t in enumerate(tickers)}
    shares  = {t: int(np.floor(dollars[t] / closes[t])) for t in tickers}
    used    = {t: shares[t] * closes[t] for t in tickers}

    invested_usd = float(np.sum(list(used.values())))
    cash_usd     = float(capital_usd - invested_usd)
    actual_w     = np.array([used[t] / capital_usd for t in tickers])
    actual_cash_w = 1.0 - actual_w.sum()

    actual_vol_daily = float(np.sqrt(max(actual_w @ Sigma @ actual_w, 0.0)))
    mu_daily = float(np.sum([preds[t] * (used[t] / capital_usd) for t in tickers]))
    mu_ann   = mu_daily * 252.0
    vol_ann  = daily_to_annual_vol(actual_vol_daily)
    exp_sharpe = (mu_daily / actual_vol_daily) * np.sqrt(252.0) if actual_vol_daily > 0 else np.nan
    var95_1d_usd = 1.65 * actual_vol_daily * capital_usd

    alloc_rows = []
    for t in tickers:
        alloc_rows.append({
            "Ticker": t,
            "Close": closes[t],
            "pred": preds[t],
            "actual_w": used[t] / capital_usd,
            "dollars": used[t],
            "shares": shares[t],
        })
    alloc_df = pd.DataFrame(alloc_rows).sort_values("Ticker").reset_index(drop=True)

    summary = pd.DataFrame([{
        "Capital ($)": round(capital_usd, 2),
        "Invested ($)": round(invested_usd, 2),
        "Cash ($)": round(cash_usd, 2),
        "Cash weight": round(actual_cash_w, 4),
        "Exp μ (daily, %)": round(mu_daily*100, 3),
        "Exp μ (annual, %)": round(mu_ann*100, 2),
        "Vol (daily, %)": round(actual_vol_daily*100, 3),
        "Vol (annual, %)": round(vol_ann*100, 2),
        "Exp Sharpe": round(exp_sharpe, 3) if np.isfinite(exp_sharpe) else np.nan,
        "1-day 95% VaR ($)": round(var95_1d_usd, 2),
        "Method": method,
        "Target Ann Vol": target_ann_vol,
        "Max Single W": max_single_w,
        "BUY thr": pos_thr,
        "Corr gate": corr_min,
    }])

    return (
        candidates[["Ticker","Date","Close","pred_combined","RollCorr"]],
        alloc_df[["Ticker","Close","pred","actual_w","dollars","shares"]],
        summary
    )

def save_slide(as_of: pd.Timestamp, alloc_df: pd.DataFrame, summary_df: pd.DataFrame):
    """Save dated CSV + Markdown for presentations."""
    csv_path = OUT_DIR / f"portfolio_plan_{as_of.date()}.csv"
    md_path  = OUT_DIR / f"portfolio_plan_{as_of.date()}.md"

    alloc_df.to_csv(csv_path, index=False)

    md = []
    md.append(f"# Portfolio Plan — {as_of.date()}\n\n")
    md.append("## Allocation\n\n")
    md.append("| Ticker | Close | pred | weight | dollars | shares |\n|---|---:|---:|---:|---:|---:|\n")
    for r in alloc_df.itertuples(index=False):
        md.append(f"| {r.Ticker} | {r.Close:.2f} | {r.pred:+.3%} | {r.actual_w:.2%} | ${r.dollars:,.2f} | {r.shares} |\n")
    md.append("\n## Summary\n\n")
    for k, v in summary_df.iloc[0].items():
        md.append(f"- **{k}**: {v}\n")
    Path(md_path).write_text("".join(md), encoding="utf-8")

    return str(csv_path), str(md_path)

try:
    _df0 = load_eval()
    DATA_MIN = pd.to_datetime(_df0["Date"].min()).normalize()
    DATA_MAX = pd.to_datetime(_df0["Date"].max()).normalize()
except Exception:
    DATA_MIN = None
    DATA_MAX = None

def clamp_date(d: pd.Timestamp) -> pd.Timestamp:
    if DATA_MIN is not None and d < DATA_MIN:
        return DATA_MIN
    if DATA_MAX is not None and d > DATA_MAX:
        return DATA_MAX
    return d

with gr.Blocks(title="AI Investor Bot — Time-travel Portfolio") as demo:
    gr.Markdown("# AI Investor Bot — Time-travel Portfolio")
    gr.Markdown(
        "Pick an **as-of date** (or use presets), then size a portfolio from the latest predictions "
        "available up to that date with a **quality gate** (rolling corr) and **target vol**."
    )

    with gr.Row():
        asof_txt  = gr.Textbox(label="As-of date (YYYY-MM-DD)", placeholder="e.g., 2024-06-30")
        btn_latest = gr.Button("Latest")
        btn_2y     = gr.Button("−2 years")
        btn_2m     = gr.Button("−2 months")

    with gr.Row():
        with gr.Column(scale=1):
            capital   = gr.Number(label="Capital ($)", value=20000, precision=0)
            pos_thr   = gr.Slider(0.0, 1.0, value=0.20, step=0.05, label="BUY threshold (+%, of next-day log return)")
            corr_gate = gr.Slider(0.00, 0.20, value=0.07, step=0.01, label="Quality gate: Rolling corr ≥")
            method    = gr.Dropdown(choices=["signal_vol","inverse_vol","equal"], value="signal_vol", label="Weight method")
            max_w     = gr.Slider(5, 50, value=25, step=1, label="Max single weight (%)")
            targ_vol  = gr.Slider(2.0, 30.0, value=10.0, step=0.5, label="Target annual volatility (%)")
        with gr.Column(scale=1):
            roll_corr = gr.Slider(20, 120, value=60, step=5, label="Rolling corr window (days)")
            roll_cov  = gr.Slider(20, 120, value=60, step=5, label="Rolling covariance window (days)")
            minp      = gr.Slider(10, 90, value=40, step=5, label="Min periods for stats")
            run_btn   = gr.Button("Run", variant="primary")

            out_csv = gr.File(label="Download allocation CSV")
            out_md  = gr.File(label="Download plan Markdown")

    gr.Markdown("### Candidates (BUY signals after quality gate)")
    out_candidates = gr.Dataframe(wrap=True)
    gr.Markdown("### Allocation (after risk scaling & share rounding)")
    out_alloc = gr.Dataframe(wrap=True)
    gr.Markdown("### Portfolio summary")
    out_summary = gr.Dataframe(wrap=True)

    out_status = gr.Textbox(label="Status", interactive=False)

    def _set_latest():
        return str(DATA_MAX) if DATA_MAX is not None else ""
    btn_latest.click(_set_latest, outputs=asof_txt)

    def _set_2y():
        if DATA_MAX is None:
            return ""
        d = pd.to_datetime(DATA_MAX) - pd.DateOffset(years=2)
        return clamp_date(d).date().isoformat()
    btn_2y.click(_set_2y, outputs=asof_txt)

    def _set_2m():
        if DATA_MAX is None:
            return ""
        d = pd.to_datetime(DATA_MAX) - pd.DateOffset(months=2)
        return clamp_date(d).date().isoformat()
    btn_2m.click(_set_2m, outputs=asof_txt)

    def _on_run(asof_str, cap, thr, corr, mth, maxw, tvol, rcw, covw, minp_):
        try:
            if asof_str and str(asof_str).strip():
                asof = pd.to_datetime(str(asof_str)).normalize()
            else:
                asof = pd.to_datetime(DATA_MAX).normalize() if DATA_MAX is not None else pd.to_datetime("today").normalize()
        except Exception:
            return (
                pd.DataFrame(), pd.DataFrame(), pd.DataFrame(),
                None, None,
                f"Invalid date: {asof_str}. Use YYYY-MM-DD."
            )

        if DATA_MIN is not None and DATA_MAX is not None:
            asof = clamp_date(asof)

        try:
            cand, alloc, summ = portfolio_as_of(
                as_of_date=asof,
                capital_usd=float(cap),
                buy_thr_pct=float(thr),
                corr_min=float(corr),
                method=str(mth),
                max_single_w_pct=float(maxw),
                target_ann_vol_pct=float(tvol),
                roll_corr_win=int(rcw),
                roll_cov_win=int(covw),
                min_periods=int(minp_),
            )
            csv_path, md_path = save_slide(asof, alloc, summ)
            status = (
                f"Plan built for {asof.date()} — files saved:\n"
                f"- {csv_path}\n- {md_path}"
            )
            return cand, alloc, summ, csv_path, md_path, status
        except Exception as e:
            return (
                pd.DataFrame(), pd.DataFrame(), pd.DataFrame(),
                None, None,
                f"Error: {e}"
            )

    run_btn.click(
        _on_run,
        inputs=[asof_txt, capital, pos_thr, corr_gate, method, max_w, targ_vol, roll_corr, roll_cov, minp],
        outputs=[out_candidates, out_alloc, out_summary, out_csv, out_md, out_status],
    )

if __name__ == "__main__":
    demo.launch()

* Running on local URL:  http://127.0.0.1:7864
* To create a public link, set `share=True` in `launch()`.